server:
  port: 8080

spring:
  application:
    name: library
  datasource:
    url: jdbc:h2:mem:library_management_system_db
    username: admin
    password:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

springdoc:
  swagger-ui:
    path: /swagger-ui
