server:
  port: 8080

spring:
  application:
    name: library
  datasource:
    url: jdbc:h2:mem:library_management_system_db;DB_CLOSE_DELAY=-1
    username: admin
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
